### PR TITLE
Update defines.hpp

### PR DESCRIPTION
**Pull request by or75**

### CODE REVIEW

**Comment by or75** [comment]
and gloves changer not work )

**Comment by singhhdev** [comment]
knife animations do work, i havent added the code for the glove changer right now

**Comment by g0T-h** [comment]
> knife animations do work, i havent added the code for the glove changer right now

It's as he says, gloves don't work but animations work for me, with the exception of Butterfly Knives, they semi-work.
Anyways, gloves are great so I'd appreciate if you could fix it :)

**Comment by singhhdev** [comment]
im working on the gloves right now!

**Pull request closed without merging**
